# Generated by Django 5.0.6 on 2024-06-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
