# Generated by Django 5.0.6 on 2024-06-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('biography', models.CharField(max_length=400)),
                ('birthday_day', models.IntegerField()),
                ('birthday_month', models.CharField(max_length=255)),
                ('birthday_year', models.IntegerField()),
            ],
        ),
    ]
