# Generated by Django 5.0.6 on 2024-07-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_customuser_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='online',
        ),
    ]
