# Generated by Django 5.0.6 on 2024-07-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_customuser_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.IntegerField(null=True)),
                ('date_send', models.DateTimeField(null=True)),
                ('to_user', models.IntegerField(null=True)),
                ('is_accept', models.BooleanField(default=False)),
                ('date_friend', models.DateTimeField(null=True)),
            ],
        ),
    ]
