# Generated by Django 5.0.6 on 2024-07-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='in_subscribe',
            field=models.BooleanField(null=True),
        ),
    ]
