# Generated by Django 5.0.6 on 2024-07-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_friends_in_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='in_subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
