# Generated by Django 5.0.6 on 2024-07-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_chat_first_user_name_chat_second_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='first_user_name',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='second_user_name',
        ),
    ]
