# Generated by Django 5.0.6 on 2024-07-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_chat_first_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='date',
            new_name='date_send',
        ),
        migrations.AddField(
            model_name='messages',
            name='date_look',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_change',
            field=models.DateTimeField(null=True),
        ),
    ]
