# Generated by Django 5.0.6 on 2024-08-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_date_messages_date_send_messages_date_look_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
