# Generated by Django 5.0.6 on 2024-08-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_customuser_online_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
