# Generated by Django 5.0.6 on 2024-08-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_bio_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
