# Generated by Django 5.0.6 on 2024-08-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_customuser_avatar_alter_bio_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.TextField(default='avatar_default.jpg'),
        ),
    ]
