# Generated by Django 5.0.6 on 2024-08-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_id',
            field=models.IntegerField(default=0),
        ),
    ]
