# Generated by Django 5.0.6 on 2024-08-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_customuser_avatar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='read',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='reader',
            field=models.IntegerField(null=True),
        ),
    ]
