# Generated by Django 5.0.6 on 2024-08-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_chat_read_chat_reader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('file_name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('only_friends_can_see', models.BooleanField()),
            ],
        ),
    ]
